name: safe_result
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/nayefradwi/safe_result

environment:
  sdk: ^3.7.2

dependencies:
  very_good_analysis: ^7.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
