name: result_flow
description: Provides a Result type (Result<T>) for robust error handling, encapsulating either a success value or an error. Includes helpers for safe execution and chaining.
version: 1.2.0
repository: https://github.com/nayefradwi/result_flow

environment:
  sdk: ^3.7.2


dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^7.0.0
